# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: 'cli.abcxyz.dev/v1alpha1'
kind: 'Template'

desc: 'Generate infrastructure needed for JVS'

inputs:
  - name: 'repo_path'
    desc: 'The path of the repo to store the generated files.'
    default: ''

  - name: 'project_id'
    desc: 'The GCP project to host the justification verification system.'

  - name: 'jvs_release_version'
    desc: 'The release version of the abcxyz/jvs. For example: 0.0.1'

  - name: 'region'
    desc: 'The default Google Cloud region to deploy resources in.'
    default: 'us-central1'

  - name: 'jvs_invoker_members'
    desc: 'The list of members that can call JVS.'
    default: '[]'

  - name: 'jvs_api_domain'
    desc: 'The JVS API domain.'

  - name: 'jvs_ui_domain'
    desc: 'The JVS UI domain.'

  - name: 'iap_support_email'
    desc: 'The IAP support email.'

  - name: 'kms_key_location'
    desc: 'The location where kms key will be created.'
    default: 'global'

  - name: 'notification_channel_email'
    desc: 'The Email address where alert notifications send to.'

  - name: 'prober_audience'
    desc: 'The cloud run url for jvs api service or app address.If not set, the cloud run url for jvs api service will be used.'
    default: ''

  - name: 'plugin_envvars'
    desc: 'Env vars for plugin.'
    default: '{}'

  - name: 'alert_enabled'
    desc: 'True if alerts are enabled, otherwise false..'
    default: 'true'

  - name: 'terraform_state_bucket'
    desc: 'The Google Cloud storage bucket for Terraform backend state'

  - name: 'terraform_state_prefix'
    desc: 'The Google Cloud storage bucket prefix for Terraform backend state'

steps:
  - desc: 'Include required files and directories'
    action: 'include'
    params:
      paths:
        - 'jvs-e2e.tf'
        - 'terraform.tf'

  - desc: 'Replace variables to define the Terraform block'
    action: 'string_replace'
    params:
      paths:
        - 'terraform.tf'
      replacements:
        - to_replace: 'REPLACE_TERRAFORM_STATE_BUCKET'
          with: '{{.terraform_state_bucket}}'

        - to_replace: 'REPLACE_TERRAFORM_STATE_PREFIX'
          with: '{{.terraform_state_prefix}}'

  - desc: 'Replace variables to define the resources'
    action: 'string_replace'
    params:
      paths:
        - 'jvs-e2e.tf'
      replacements:
        - to_replace: 'REPLACE_PROJECT_ID'
          with: '{{.project_id}}'

        - to_replace: 'REPLACE_JVS_RELEASE_VERSION'
          with: '{{.jvs_release_version}}'

        - to_replace: 'REPLACE_REGION'
          with: '{{.region}}'

        - to_replace: 'REPLACE_KMS_KEY_LOCATION'
          with: '{{.kms_key_location}}'

        - to_replace: 'REPLACE_JVS_INVOKE_MEMBERS'
          with: '{{.jvs_invoker_members}}'

        - to_replace: 'REPLACE_JVS_API_DOMAIN'
          with: '{{.jvs_api_domain}}'

        - to_replace: 'REPLACE_JVS_UI_DOMAIN'
          with: '{{.jvs_ui_domain}}'

        - to_replace: 'REPLACE_IAP_SUPPORT_EMAIL'
          with: '{{.iap_support_email}}'

        - to_replace: 'REPLACE_NOTIFICATION_CHANNEL_EMAIL'
          with: '{{.notification_channel_email}}'

        - to_replace: 'REPLACE_PROBER_AUDIENCE'
          with: '{{.prober_audience}}'

        - to_replace: 'REPLACE_PLUGIN_ENVVARS'
          with: '{{.plugin_envvars}}'

        - to_replace: 'REPLACE_ALERT_ENABLED'
          with: '{{.alert_enabled}}'
