# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

env:
  # Global env vars for Go build.
  - 'CGO_ENABLED=0'
  - 'GO111MODULE=on'
  - 'GOPROXY=https://proxy.golang.org,direct'

before:
  hooks:
    - 'go mod tidy'

# Duplicate the build from .goreleaser.yaml.
builds:
  -
    id: 'jvsctl'
    main: './cmd/jvsctl'
    binary: 'jvsctl'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - '-a'
      - '-trimpath'
    ldflags:
      - '-s'
      - '-w'
      - '-X={{ .ModulePath }}/internal/version.name=jvsctl'
      - '-X={{ .ModulePath }}/internal/version.version={{ .Version }}'
      - '-X={{ .ModulePath }}/internal/version.commit={{ .Commit }}'
      - '-extldflags=-static'
    goos:
      - 'darwin'
      - 'linux'
      - 'windows'
    goarch:
      - 'amd64'
      - 'arm64'

dockers:
  -
    ids:
      - 'jvsctl'
    use: 'buildx'
    goos: 'linux'
    goarch: 'amd64'
    image_templates:
      - '{{ .Env.CONTAINER_REGISTRY }}/jvsctl:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}-amd64'
    build_flag_templates:
      - '--platform=linux/amd64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=JVS command line'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.name=jvsctl'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.title=jvsctl'
      - '--label=org.opencontainers.image.version={{ .Version }}'

  -
    ids:
      - 'jvsctl'
    use: 'buildx'
    goos: 'linux'
    goarch: 'arm64'
    image_templates:
      - '{{ .Env.CONTAINER_REGISTRY }}/jvsctl:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}-arm64'
    build_flag_templates:
      - '--platform=linux/arm64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=JVS command line'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.name=jvsctl'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.title=jvsctl'
      - '--label=org.opencontainers.image.version={{ .Version }}'

  -
    ids:
      - 'jvsctl'
    use: 'buildx'
    goos: 'linux'
    goarch: 'amd64'
    image_templates:
      - '{{ .Env.CONTAINER_REGISTRY }}/jvs-prober:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}-amd64'
    dockerfile: './prober/prober.dockerfile'
    extra_files:
      - './prober/prober.sh'
    build_flag_templates:
      - '--platform=linux/amd64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=Prober for jvs'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.name=jvs-prober'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.title=jvs-prober'
      - '--label=org.opencontainers.image.version={{ .Version }}'

  -
    ids:
      - 'jvsctl'
    use: 'buildx'
    goos: 'linux'
    goarch: 'arm64'
    image_templates:
      - '{{ .Env.CONTAINER_REGISTRY }}/jvs-prober:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}-arm64'
    dockerfile: './prober/prober.dockerfile'
    extra_files:
      - './prober/prober.sh'
    build_flag_templates:
      - '--platform=linux/arm64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=Prober for jvs'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.name=jvs-prober'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.title=jvs-prober'
      - '--label=org.opencontainers.image.version={{ .Version }}'

docker_manifests:
  -
    name_template: '{{ .Env.CONTAINER_REGISTRY }}/jvsctl:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}'
    image_templates:
      - '{{ .Env.CONTAINER_REGISTRY }}/jvsctl:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}-amd64'
      - '{{ .Env.CONTAINER_REGISTRY }}/jvsctl:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}-arm64'

  -
    name_template: '{{ .Env.CONTAINER_REGISTRY }}/jvs-prober:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}'
    image_templates:
      - '{{ .Env.CONTAINER_REGISTRY }}/jvs-prober:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}-amd64'
      - '{{ .Env.CONTAINER_REGISTRY }}/jvs-prober:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}-arm64'


# TODO(#144): Follow up on sign.


# Disable SCM release we only want docker release here.
release:
  disable: true
