// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: jvs_service.proto

package v0connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v0 "github.com/abcxyz/jvs/apis/v0"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// JVSServiceName is the fully-qualified name of the JVSService service.
	JVSServiceName = "abcxyz.jvs.JVSService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// JVSServiceCreateJustificationProcedure is the fully-qualified name of the JVSService's
	// CreateJustification RPC.
	JVSServiceCreateJustificationProcedure = "/abcxyz.jvs.JVSService/CreateJustification"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	jVSServiceServiceDescriptor                   = v0.File_jvs_service_proto.Services().ByName("JVSService")
	jVSServiceCreateJustificationMethodDescriptor = jVSServiceServiceDescriptor.Methods().ByName("CreateJustification")
)

// JVSServiceClient is a client for the abcxyz.jvs.JVSService service.
type JVSServiceClient interface {
	CreateJustification(context.Context, *connect.Request[v0.CreateJustificationRequest]) (*connect.Response[v0.CreateJustificationResponse], error)
}

// NewJVSServiceClient constructs a client for the abcxyz.jvs.JVSService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewJVSServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) JVSServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &jVSServiceClient{
		createJustification: connect.NewClient[v0.CreateJustificationRequest, v0.CreateJustificationResponse](
			httpClient,
			baseURL+JVSServiceCreateJustificationProcedure,
			connect.WithSchema(jVSServiceCreateJustificationMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// jVSServiceClient implements JVSServiceClient.
type jVSServiceClient struct {
	createJustification *connect.Client[v0.CreateJustificationRequest, v0.CreateJustificationResponse]
}

// CreateJustification calls abcxyz.jvs.JVSService.CreateJustification.
func (c *jVSServiceClient) CreateJustification(ctx context.Context, req *connect.Request[v0.CreateJustificationRequest]) (*connect.Response[v0.CreateJustificationResponse], error) {
	return c.createJustification.CallUnary(ctx, req)
}

// JVSServiceHandler is an implementation of the abcxyz.jvs.JVSService service.
type JVSServiceHandler interface {
	CreateJustification(context.Context, *connect.Request[v0.CreateJustificationRequest]) (*connect.Response[v0.CreateJustificationResponse], error)
}

// NewJVSServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewJVSServiceHandler(svc JVSServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	jVSServiceCreateJustificationHandler := connect.NewUnaryHandler(
		JVSServiceCreateJustificationProcedure,
		svc.CreateJustification,
		connect.WithSchema(jVSServiceCreateJustificationMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/abcxyz.jvs.JVSService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case JVSServiceCreateJustificationProcedure:
			jVSServiceCreateJustificationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedJVSServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedJVSServiceHandler struct{}

func (UnimplementedJVSServiceHandler) CreateJustification(context.Context, *connect.Request[v0.CreateJustificationRequest]) (*connect.Response[v0.CreateJustificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("abcxyz.jvs.JVSService.CreateJustification is not implemented"))
}
