name: 'test (unit)'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  # Go server
  go_lint_server:
    uses: 'abcxyz/pkg/.github/workflows/go-lint.yml@main'
    with:
      go_version: '1.18'

  go_test_server:
    uses: 'abcxyz/pkg/.github/workflows/go-test.yml@main'
    with:
      go_version: '1.18'
      go_packages: './apis/... ./cmd/... ./pkg/...'

  # Go client
  go_lint_client:
    uses: 'abcxyz/pkg/.github/workflows/go-lint.yml@main'
    with:
      directory: 'client-lib/go'
      go_version: '1.18'

  go_test_client:
    uses: 'abcxyz/pkg/.github/workflows/go-test.yml@main'
    with:
      directory: 'client-lib/go'
      go_version: '1.18'
      go_packages: './...'

  # Java client
  java_lint_client:
    uses: 'abcxyz/pkg/.github/workflows/java-lint.yml@main'
    with:
      java_version: '11'

  java_test_client:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'

      - name: Run test script
        run: |-
          mvn clean test --no-transfer-progress -f client-lib/java
